# Generated by Django 4.0 on 2021-12-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
