# Generated by Django 4.0 on 2021-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_client', '0002_rename_person_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persons',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persons',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persons',
            name='telephone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
