# Generated by Django 4.0 on 2021-12-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_client', '0004_firstname_alter_persons_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='firstname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_firstname', to='bd_client.firstname'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
