# Generated by Django 4.0 on 2021-12-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_client', '0005_alter_persons_firstname_alter_persons_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='persons',
            name='lastname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_lastname', to='bd_client.firstname'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='surname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_surname', to='bd_client.firstname'),
        ),
    ]
