# Generated by Django 4.0 on 2021-12-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_client', '0006_lastname_surname_alter_persons_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstname',
            name='firstname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lastname',
            name='lastname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='surname',
            name='surname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
